import 'package:pocketotaku/models/content_model.dart';

class Anime extends Content {
  String type;
  int episodes;
  String aired;
  String premiered;
  String broadcast;
  String producers;
  String licensors;
  String studio;
  String source;
  String duration;
  String ageRating;

  Anime({
    required this.type,
    required this.episodes,
    required this.aired,
    required this.premiered,
    required this.broadcast,
    required this.producers,
    required this.licensors,
    required this.studio,
    required this.source,
    required this.duration,
    required this.ageRating,
    required String title,
    required String image,
    required String synopsis,
    required double rating,
    required String demographic,
    required String genres,
    required String status,
    required String tag,
  }) : super(title: title, image: image, synopsis: synopsis, rating: rating, demographic: demographic,
      genres: genres, status: status, tag: tag);
}

var animeList = [
  Anime(
    title: 'Fullmetal Alchemist: Brotherhood',
    image:'assets/images/animes/fmab.jpg',
    synopsis: 'After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality. Ignoring the alchemical principle banning human transmutation, the boys attempted to bring their recently deceased mother back to life. Instead, they suffered brutal personal loss: Alphonse\'s body disintegrated while Edward lost a leg and then sacrificed an arm to keep Alphonse\'s soul in the physical realm by binding it to a hulking suit of armor. The brothers are rescued by their neighbor Pinako Rockbell and her granddaughter Winry. Known as a bio-mechanical engineering prodigy, Winry creates prosthetic limbs for Edward by utilizing "automail," a tough, versatile metal used in robots and combat armor. After years of training, the Elric brothers set off on a quest to restore their bodies by locating the Philosopher\'s Stone—a powerful gem that allows an alchemist to defy the traditional laws of Equivalent Exchange. As Edward becomes an infamous alchemist and gains the nickname "Fullmetal," the boys\' journey embroils them in a growing conspiracy that threatens the fate of the world.',
    rating: 9.13,
    demographic: 'Shounen',
    genres: 'Action, Adventure, Drama, Fantasy',
    status: 'Finished Airing',
    type: 'TV',
    episodes: 64,
    aired: 'Apr 5, 2009 to Jul 4, 2010',
    premiered: 'Spring 2009',
    broadcast: 'Sundays at 17:00 (JST)',
    producers: 'Aniplex, Square Enix, Mainichi Broadcasting System, Studio Moriken',
    licensors: 'Funimation, Aniplex of America',
    studio: 'Bones',
    source: 'Manga',
    duration: '24 min. per ep.',
    ageRating: 'R - 17+ (violence & profanity)',
    tag: 'FMAB'
  ),
  Anime(
    title: 'Koe no Katachi',
    image: 'assets/images/animes/koenokatachi.jpg',
    synopsis: 'As a wild youth, elementary school student Shouya Ishida sought to beat boredom in the cruelest ways. When the deaf Shouko Nishimiya transfers into his class, Shouya and the rest of his class thoughtlessly bully her for fun. However, when her mother notifies the school, he is singled out and blamed for everything done to her. With Shouko transferring out of the school, Shouya is left at the mercy of his classmates. He is heartlessly ostracized all throughout elementary and middle school, while teachers turn a blind eye. Now in his third year of high school, Shouya is still plagued by his wrongdoings as a young boy. Sincerely regretting his past actions, he sets out on a journey of redemption: to meet Shouko once more and make amends. Koe no Katachi tells the heartwarming tale of Shouya\'s reunion with Shouko and his honest attempts to redeem himself, all while being continually haunted by the shadows of his past.',
    rating: 8.95,
    demographic: 'Shounen',
    genres: 'Drama, Romance',
    status: 'Finished Airing',
    type: 'Movie',
    episodes: 1,
    aired: 'Sep 17, 2016',
    premiered: 'Sep 17, 2016',
    broadcast: 'Sep 17, 2016',
    producers: 'Shochiku, Pony Canyon, Kodansha, ABC Animation, Quaras',
    licensors: 'Eleven Arts, NYAV Post',
    studio: 'Kyoto Animation',
    source: 'Manga',
    duration: '2 hr. 10 min.',
    ageRating: 'PG-13 - Teens 13 or older',
    tag: 'koenokatachi'
  ),
  Anime(
    title: 'Clannad: After Story',
    image: 'assets/images/animes/clannadafterstory.jpg',
    synopsis: 'Clannad: After Story, the sequel to the critically acclaimed slice-of-life series Clannad, begins after Tomoya Okazaki and Nagisa Furukawa graduate from high school. Together, they experience the emotional rollercoaster of growing up. Unable to decide on a course for his future, Tomoya learns the value of a strong work ethic and discovers the strength of Nagisa\'s support. Through the couple\'s dedication and unity of purpose, they push forward to confront their personal problems, deepen their old relationships, and create new bonds. Time also moves on in the Illusionary World. As the plains grow cold with the approach of winter, the Illusionary Girl and the Garbage Doll are presented with a difficult situation that reveals the World\'s true purpose. Based on the visual novel by Key and produced by Kyoto Animation, Clannad: After Story is an impactful drama highlighting the importance of family and the struggles of adulthood.',
    rating: 8.94,
    demographic: 'Seinen',
    genres: 'Drama, Romance, Supernatural',
    status: 'Finished Aired',
    type: 'TV',
    episodes: 24,
    aired: 'Oct 3, 2008 to Mar 27, 2009',
    premiered: 'Fall 2008',
    broadcast: 'Fridays at 01:59 (JST)',
    producers: 'Pony Canyon, TBS, Rakuonsha, Animation Do',
    licensors: 'Sentai Filmworks',
    studio: 'Kyoto Animation',
    source: 'Visual Novel',
    duration: '24 min. per ep.',
    ageRating: 'PG-13 - Teens 13 or older',
    tag: 'clannad'
  ),
  Anime(
    title: 'Kimi no Na wa',
    image: 'assets/images/animes/yourname.jpg',
    synopsis: 'Mitsuha Miyamizu, a high school girl, yearns to live the life of a boy in the bustling city of Tokyo—a dream that stands in stark contrast to her present life in the countryside. Meanwhile in the city, Taki Tachibana lives a busy life as a high school student while juggling his part-time job and hopes for a future in architecture. One day, Mitsuha awakens in a room that is not her own and suddenly finds herself living the dream life in Tokyo—but in Taki\'s body! Elsewhere, Taki finds himself living Mitsuha\'s life in the humble countryside. In pursuit of an answer to this strange phenomenon, they begin to search for one another. Kimi no Na wa. revolves around Mitsuha and Taki\'s actions, which begin to have a dramatic impact on each other\'s lives, weaving them into a fabric held together by fate and circumstance.',
    rating: 8.86,
    demographic: 'Shounen',
    genres: 'Drama, Supernatural, Romance',
    status: 'Finished Airing',
    type: 'Movie',
    episodes: 1,
    aired: 'Aug 26, 2016',
    premiered: 'Aug 26, 2016',
    broadcast: 'Aug 26, 2016',
    producers: 'Toho, Sound Team Don Juan, Amuse, JR East Marketing & Communications, Kadokawa, voque ting',
    licensors: 'Funimation, NYAV Post',
    studio: 'CoMix Wave Films',
    source: 'Original',
    duration: '1 hr. 46 min.',
    ageRating: 'PG-13 - Teens 13 or older',
    tag: 'yourname'
  ),
  Anime(
    title: 'Mushoku Tensei: Isekai Ittara Honki Dasu Part 2',
    image: 'assets/images/animes/mushokup2.jpg',
    synopsis: 'After the mysterious mana calamity, Rudeus Greyrat and his fierce student Eris Boreas Greyrat are teleported to the Demon Continent. There, they team up with their newfound companion Ruijerd Supardia—the former leader of the Superd\'s Warrior group—to form "Dead End," a successful adventurer party. Making a name for themselves, the trio journeys across the continent to make their way back home to Fittoa. Following the advice he received from the faceless god Hitogami, Rudeus saves Kishirika Kishirisu, the Great Emperor of the Demon World, who rewards him by granting him a strange power. Now, as Rudeus masters the powerful ability that offers a number of new opportunities, it might prove to be more than what he bargained for when unexpected dangers threaten to hinder their travels.',
    rating: 8.74,
    demographic: 'Shounen',
    genres: 'Drama, Fantasy, Ecchi, Isekai, Reincarnation',
    status: 'Finished Airing',
    type: 'TV',
    episodes: 12,
    aired: 'Oct 4, 2021 to Dec 20, 2021',
    premiered: 'Fall 2021',
    broadcast: 'Mondays at 00:00 (JST)',
    producers: 'Frontier Works, Tokyo MX, Hakuhodo DY Music & Pictures, BS11, Egg Firm, GREE Entertainment',
    licensors: 'Funimation',
    studio: 'Studio Bind',
    source: 'Light Novel',
    duration: '23 min. per ep.',
    ageRating: 'R - 17+ (violence & profanity)',
    tag: 'mushokutensei'
  ),
  Anime(
    title: '86 Part 2',
    image: 'assets/images/animes/86p2.jpg',
    synopsis: 'The disappearance of the Spearhead Squadron beyond the horizon does little to hide the intensity of the Republic of San Magnolia\'s endless propaganda. Vladilena Milizé continues to operate as "Handler One," the commander of yet another dehumanized 86th faction\'s squadron in the continuous war against the Legion. On the Western Front, Shinei Nouzen and his squad are quarantined in a military base controlled by the Federal Republic of Giad, formerly known as the Giadian Empire. The newly-established government grants the saved Eighty-Six full citizenship and freedom. Housed by the president Ernst Zimmerman himself, the group meets his adoptive daughter and the last Empress, Augusta Frederica Adel-Adler. However, within the calm of this tender society, Shinei and his team feel that their purpose is on the battlefield. Before long, they are once again in the midst of the Legion\'s onslaught as a part of the Federacy\'s Nordlicht Squadron, accompanied by Augusta Frederica. But, as history repeats itself, they realize that no matter the side, death and pain on the front lines are the only comfort they know.',
    rating: 8.71,
    demographic: 'Shounen',
    genres: 'Action, Drama, Mecha, Millitary, Sci-Fi',
    status: 'Finished Airing',
    type: 'TV',
    episodes: 12,
    aired: 'Oct 3, 2021 to Mar 19, 2022',
    premiered: 'Fall 2021',
    broadcast: 'Sundays at 00:00 (JST)',
    producers: 'Aniplex, Kadokawa, Bandai Spirits',
    licensors: 'None',
    studio: 'A-1 Pictures',
    source: 'Light Novel',
    duration: '23 min. per ep.',
    ageRating: 'R - 17+ (violence & profanity)',
    tag: '86'
  ),
  Anime(
    title: 'Fate/stay night Movie: Heaven\'s Feel - III. Spring Song',
    image: 'assets/images/animes/fateheavenfeel3.jpg',
    synopsis: 'The Fifth Holy Grail War in Fuyuki City has reached a turning point in which the lives of all participants are threatened as the hidden enemy finally reveals itself. As Shirou Emiya, Rin Toosaka, and Illyasviel von Einzbern discover the true, corruptive nature of the shadow that has been rampaging throughout the city, they realize just how dire the situation is. In order to protect their beloved ones, the group must hold their own against the seemingly insurmountable enemy force—even if some of those foes were once their allies, or perhaps, something more intimate. As the final act of this chaotic war commences, the ideals Shirou believes will soon be challenged by an excruciating dilemma: is it really possible to save a world where everything seems to have gone wrong?',
    rating: 8.71,
    demographic: 'Shounen',
    genres: 'Action, Fantasy, Supernatural',
    status: 'Finished Airing',
    type: 'Movie',
    episodes: 1,
    aired: 'Aug 15, 2020',
    premiered: 'Aug 15, 2020',
    broadcast: 'Aug 15, 2020',
    producers: 'Aniplex, Notes, Kadokawa',
    licensors: 'Aniplex of America',
    studio: 'ufotable',
    source: 'Visual Novel',
    duration: '2 hr. 2 min.',
    ageRating: 'R - 17+ (violence & profanity)',
    tag: 'fsn'
  ),
  Anime(
    title: 'Code Geass: Hangyaku no Lelouch',
    image: 'assets/images/animes/codegeass.jpg',
    synopsis: 'In the year 2010, the Holy Empire of Britannia is establishing itself as a dominant military nation, starting with the conquest of Japan. Renamed to Area 11 after its swift defeat, Japan has seen significant resistance against these tyrants in an attempt to regain independence. Lelouch Lamperouge, a Britannian student, unfortunately finds himself caught in a crossfire between the Britannian and the Area 11 rebel armed forces. He is able to escape, however, thanks to the timely appearance of a mysterious girl named C.C., who bestows upon him Geass, the "Power of Kings." Realizing the vast potential of his newfound "power of absolute obedience," Lelouch embarks upon a perilous journey as the masked vigilante known as Zero, leading a merciless onslaught against Britannia in order to get revenge once and for all.',
    rating: 8.70,
    demographic: 'Shounen',
    genres: 'Action, Drama, Mecha, Millitary, School, Sci-Fi, Super Power',
    status: 'Finished Airing',
    type: 'TV',
    episodes: 25,
    aired: 'Oct 6, 2006 to Jul 29, 2007',
    premiered: 'Fall 2006',
    broadcast: 'Fridays at 01:25 (JST)',
    producers: 'Bandai Visual, Mainichi Broadcasting System, Bandai, Sony Music Entertainment, Bandai Namco Entertainment, Hakuhodo DY Media Partners',
    licensors: 'Funimation, Bandai Entertainment',
    studio: 'Sunrise',
    source: 'Original',
    duration: '24 min. per ep.',
    ageRating: 'R - 17+ (violence & profanity)',
    tag: 'codegeass'
  ),
  Anime(
    title: 'Violet Evergarden',
    image: 'assets/images/animes/violetevergarden.jpg',
    synopsis: 'The Great War finally came to an end after four long years of conflict; fractured in two, the continent of Telesis slowly began to flourish once again. Caught up in the bloodshed was Violet Evergarden, a young girl raised for the sole purpose of decimating enemy lines. Hospitalized and maimed in a bloody skirmish during the War\'s final leg, she was left with only words from the person she held dearest, but with no understanding of their meaning. Recovering from her wounds, Violet starts a new life working at CH Postal Services after a falling out with her new intended guardian family. There, she witnesses by pure chance the work of an "Auto Memory Doll," amanuenses that transcribe people\'s thoughts and feelings into words on paper. Moved by the notion, Violet begins work as an Auto Memory Doll, a trade that will take her on an adventure, one that will reshape the lives of her clients and hopefully lead to self-discovery.',
    rating: 8.67,
    demographic: 'Shounen',
    genres: 'Drama, Fantasy, Slice of Life',
    status: 'Finished Airing',
    type: 'TV',
    episodes: 13,
    aired: 'Jan 11, 2018 to Apr 5, 2018',
    premiered: 'Winter 2018',
    broadcast: 'Thursdays at 00:00 (JST)',
    producers: 'Lantis, Pony Canyon, Rakuonsha, ABC Animation',
    licensors: 'Funimation',
    studio: 'Kyoto Animation',
    source: 'Light Novel',
    duration: '24 min. per ep.',
    ageRating: 'PG-13 - Teens 13 or older',
    tag: 'violet'
  ),
  Anime(
    title: 'Evangelion: 3.0+1.0 Thrice Upon a Time',
    image: 'assets/images/animes/evangelion3.01.0.jpg',
    synopsis: 'Following NERV\'s failed attempt to retrieve the Spears of Longinus and carry out the Human Instrumentality Project, the destruction caused by the Fourth Impact has been largely averted. In a state of disarray, Shinji Ikari, Asuka Langley Shikinami, and Rei Ayanami travel to Village 3—a survivor settlement free from Earth\'s ruination. There, Shinji slowly comes to terms with his past, developing an entirely different life from his days as an Evangelion pilot. Meanwhile, Nerv makes preparations to continue the Instrumentality Project by means of a new Impact. When WILLE\'s main aerial battleship arrives at the village, Shinji decides to board, believing that he can help by piloting an Evangelion. As new secrets are uncovered and a battle between WILLE and NERV approaches, the future of Earth hangs in the balance. Can Shinji save humanity and the rest of the world one last time?',
    rating: 8.64,
    demographic: 'Shounen',
    genres: 'Action, Drama, Mecha, Psychological, Sci-Fi',
    status: 'Finished Airing',
    type: 'Movie',
    episodes: 1,
    aired: 'Mar 8, 2021',
    premiered: 'Mar 8, 2021',
    broadcast: 'Mar 8, 2021',
    producers: 'KlockWorx',
    licensors: 'None',
    studio: 'Khara',
    source: 'Original',
    duration: '2 hr. 35 min.',
    ageRating: 'PG-13 - Teens 13 or older',
    tag: 'evangelion'
  ),
];